#!/bin/bash
set -e

CGO_ENABLED=0

BUILD_DIR=${BUILD_DIR:-../../bin}
BUILD_BIN=${1:-tsa}

OUTPUT="${BUILD_DIR}/${BUILD_BIN}"

source $(dirname $0)/version

GITSTATE="clean"
if [ -n "$DIRTY" ]; then
	GITSTATE="dirty"
fi

CONST="-X github.com/kassisol/tsa/version.Version=${VERSION} -X github.com/kassisol/tsa/version.GitCommit=${COMMIT} -X github.com/kassisol/tsa/version.GitState=${GITSTATE} -X github.com/kassisol/tsa/version.BuildDate=$(date +%s)"

LDFLAGS=${LDFLAGS:-"-linkmode external -extldflags -static -s -w"}

cd $(dirname $0)/..
cd cmd/${BUILD_BIN}

echo " Building ${BUILD_BIN} ${VERSION} from ${COMMIT} on ${ARCH}"

if [ "$CROSS" = 1 ]; then
	GOOS=darwin go build -ldflags "${CONST}" -o ${OUTPUT}-Darwin-x86_64
	GOARCH=arm64 go build -ldflags "${CONST}" -o ${OUTPUT}-Linux-arm64
	GOARCH=arm go build -ldflags "${CONST}" -o ${OUTPUT}-Linux-arm
	go build -ldflags "${CONST} ${LDFLAGS}" -o ${OUTPUT}-Linux-x86_64

	strip --strip-all ${OUTPUT}-Linux-x86_64

	echo Built ${OUTPUT}-Linux-x86_64
else
	go build -ldflags "${CONST} ${LDFLAGS}" -o ${OUTPUT}

	strip --strip-all ${OUTPUT}

	echo Built ${OUTPUT}
fi
